# Generated by Django 5.2 on 2025-04-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="키즈카페",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("시설명", models.TextField(blank=True, null=True)),
                ("자치구명", models.TextField(blank=True, null=True)),
                ("행정동명", models.TextField(blank=True, null=True)),
                ("우편번호", models.TextField(blank=True, null=True)),
                ("기본주소", models.TextField(blank=True, null=True)),
                ("상세주소", models.TextField(blank=True, null=True)),
                ("연락처", models.TextField(blank=True, null=True)),
                ("사용료무료여부", models.TextField(blank=True, null=True)),
                ("운영일", models.TextField(blank=True, null=True)),
                ("휴관일", models.TextField(blank=True, null=True)),
                ("신청가능연령령", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "night_table",
                "managed": False,
            },
        ),
    ]
