# Generated by Django 5.2 on 2025-04-08 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_키즈카페"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="키즈카페",
            table="kids",
        ),
    ]
